### ISSUE TITLE
Feature Request: RDF Collection Operators

### ISSUE THREAD

**Issue by blake-regalia** [sebferre/sparklis#1]
In this example, we select the 'has' predicate `items` of a certain class `unordered list`. The range of `items` is an RDF collection, which enumerates the `first` and `rest` predicates of the associated blank node:
![Screen Shot 2020-11-23 at 12 21 23 PM](https://user-images.githubusercontent.com/1456400/100011575-c641ca00-2d86-11eb-97ce-3a9fdb171c32.png)
It would be great to have some operator or special relation that allows the user to search within the collection similar to using the SPARQL property path `rdf:rest*/rdf:first`.

**Comment by sebferre** [comment]
Thanks for the suggestion. It is indeed useful.
I added a pseudo-property rdf:item, suggested along rdf:first, and translated to rdf:rest*/rdf:first.
