### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by joschne** [sebferre/sparklis#12]
At Geovistory.org we love sparklis and we'd like to host a (preconfigured) instance of sparklis in the context of our project (and link it [here](https://www.geovistory.org/data)). 

All our services are hosted as docker containers (on Kubernetes). We're therefore planning to create a lightweight docker image for sparklis (based on nginx). 

We could do it on our own, but since this project is open-source we'd rather do it together with you and publish an 'official' sparklis docker image on hub.docker.com (or similar). 

If you are interested, we can fork this repo and create a PR in which we add a new GitHub workflow that versions sparklis (semver) and builds and pushes a docker image to hub.docker.com. We'd also extend the readme accordingly.

Are you interested?

**Comment by sebferre** [comment]
Yes, you are welcome, provided that you keep the license and credentials.

**Comment by joschne** [comment]
Thank you for the positive answer. We'll not change license and/or credentials. You'll hear from me, in the best case with a PR. I expect that this PR will then need a small review from your side, e.g. to agree on the name of the (public) docker image. Have a nice day!
