### ISSUE TITLE
FILTER with !=

### ISSUE THREAD

**Issue by arrascue** [sebferre/sparklis#20]
Hi, 
I was trying to get the following information against the Mondial endpoint: 
`(Pair of) Countries  that are reachable by crossing two countries`

That works. I just start from "every country" and then traverse the "has neighbor" predicate twice. 
This brings me in some cases to the country from which the traversal starts:

`Indonesia -> Malaysia -> Indonesia`.
Hence I wanted to add a condition that excludes that case, but I could not make the "!=" properly work in the interface.

This is the closest I got:
![image](https://github.com/user-attachments/assets/bf144bdd-632d-4006-b538-440adc3539cd)
returns
![image](https://github.com/user-attachments/assets/9ee8cd55-635e-42fd-8bb9-168cd30abc04)
This is translates to `BIND` and cannot find the `FILTER` option afterwards.

I'd appreciate any help.
Thank you.
Anthony

**Comment by sebferre** [comment]
Hi,
actually, you are just one click from the solution. :)
When the focus is on the Boolean expression, it uses a BIND to show the value of the expression.
By moving the focus out of the expression, on the 'where' keyword or on the first country for instance,
the BIND will be replaced by a FILTER with the expected result.
This behavior is useful to control that the Boolean expression works as expected by showing the false cases as well as the true cases.
Hope this helps

**Comment by sebferre** [comment]
By the way, here is another solution.
![Screenshot from 2024-12-13 14-15-17](https://github.com/user-attachments/assets/a8e5f169-1fae-4850-b5b6-1fed850ce52f)
The sequence of actions is:
- every country
- that has a neighbor
- that has a neighbor
- the country (middle suggestions)
- not (hamburger menu) on the focus 'the country'
- something that is (hamburger menu)

The last steps are not so intuitive but it is shorter than going through the country codes.

**Comment by arrascue** [comment]
Thanks a lot.  It worked :-)

**Comment by arrascue** [comment]
Thanks a lot. Both suggestions worked :-)
