### ISSUE TITLE
Alert error when selecting a concept

### ISSUE THREAD

**Issue by jli2025** [sebferre/sparklis#3]
Hi, when I try some endpoints on Sparklis it always alert an error 'The query was not understood by the SPARQL endpoint...'. And here is the steps to trigger this problem:
1. I set the endpoint to BAG datasets, and select the concept 'pand', now the sentence is 'give me every pand'.[ link](http://www.irisa.fr/LIS/ferre/sparklis/?endpoint=https%3A//api.labs.kadaster.nl/datasets/kadaster/bag/services/bag-1/sparql&sparklis-query=%5BVId%5DReturn%28Det%28An%281%2CModif%28Select%2CUnordered%29%2CClass%28%22http%3A//bag.basisregistraties.overheid.nl/def/bag%23Pand%22%29%29%2CNone%29%29&sparklis-path=D)
2. Then I got the results of that query, but it alert that error, and the corresponding relations of that concept didn't pop up. There should be relations like " has an geometry of", but instead there are only some basic relations here.
3. To continue the query, I select a relation 'that has a type'.
4. Now I click the 'pand' in the sentence, this time the corresponding relations appear, I am able to select 'that has a geometry' to continue the query. [link](http://www.irisa.fr/LIS/ferre/sparklis/?endpoint=https%3A//api.labs.kadaster.nl/datasets/kadaster/bag/services/bag-1/sparql&sparklis-query=%5BVId%5DReturn%28Det%28An%281%2CModif%28Select%2CUnordered%29%2CClass%28%22http%3A//bag.basisregistraties.overheid.nl/def/bag%23Pand%22%29%29%2CSome%28Rel%28%22http%3A//www.w3.org/1999/02/22-rdf-syntax-ns%23type%22%2CFwd%2CDet%28An%28103%2CModif%28Select%2CUnordered%29%2CThing%29%2CNone%29%29%29%29%29&sparklis-path=D)

When I got that error I checked the query at console, but it is a very complicated query with many UNION, which is not understandable.

**Comment by sebferre** [comment]
Hi, thanks for the detailed report.

After investigation, I found that this comes from a query size limit on the endpoint.
If you set the maximum number of results down to 100 (in Configuration > Endpoint and queries), it works.
When you add the relation 'that has a type', there are twice less retrieved entities as each entity has two types, and hence counts as two results. This is why it works in the second case.

The query is indeed complex, it is designed to get a fairer set of relations from the small sample of entities.
One thing I could do would be to add a configuration element to fallback on a simpler query.

**Comment by jli2025** [comment]
Hi, thanks very much for the answer! It works well for me after changing the results number to 100.

**Comment by sebferre** [comment]
Closing the issue as it can be solved by playing with the configuration options.
