### ISSUE TITLE
Visualizing query results on map

### ISSUE THREAD

**Issue by jli2025** [sebferre/sparklis#4]
Hi! I tried to perform a query on geo-objects, with the geometry property. But I cannot see the results on map (the 'map' option is in grey). Is it because the encoding format of geometry (WKT) is not supported? [link](http://www.irisa.fr/LIS/ferre/sparklis/?endpoint=https%3A//api.labs.kadaster.nl/datasets/kadaster/bag/services/bag/sparql&sparklis-query=%5BVId%5DReturn%28Det%28An%281%2CModif%28Select%2CUnordered%29%2CClass%28%22http%3A//bag.basisregistraties.overheid.nl/def/bag%23Pand%22%29%29%2CSome%28Rel%28%22http%3A//www.opengis.net/ont/geosparql%23hasGeometry%22%2CFwd%2CDet%28An%2875%2CModif%28Select%2CUnordered%29%2CThing%29%2CSome%28Rel%28%22http%3A//www.opengis.net/ont/geosparql%23asWKT%22%2CFwd%2CDet%28An%28111%2CModif%28Select%2CUnordered%29%2CThing%29%2CNone%29%29%29%29%29%29%29%29&sparklis-path=DDDDD&max_results=100)
And when I switch to the YASGUI, the result can be displayed on the map.

**Comment by sebferre** [comment]
Hi! WKT is indeed not supported by Sparklis. To see results on the map, the special property 'has a geolocation' must be selected. It is shown in red in the list of suggested classes and properties. It is based on one of the following vocabs: wgs84, vcard, schema.org. It is also supported in Wikidata.
