### ISSUE TITLE
Schema.org

### ISSUE THREAD

**Issue by kad-beekw** [sebferre/sparklis#5]
Thanks for creating this great query builder!

I notice that geospatial data is specifically extracted for the Schema.org vocabulary ([placed in the code where this happens](https://github.com/sebferre/sparklis/blob/874b1002176ec948e7f1cca9801c3e0b1b2657b2/rdf.ml#L72-L76)).

This currently uses the old `http://schema.org/` prefix.  In more recent versions, Schema.org switched to the `https://schema.org/` prefix (notice the `s`).  Could variants for this new prefix be added to the Sparklis configuration?  I can imagine that the old prefix will still be used by some people for some amount of time.

I am specifically looking at the two geospatial properties with Schema.org prefix (`sdo:latitude` and `sdo:longitude`), but the same may apply for other places in Sparklis where Schema.org may be used for other purposes.

For testing purposes you can make used of the following query over our endpoint: <https://rebrand.ly/yvuputi>

**Comment by sebferre** [comment]
Thank you for notifying me the change. As suggested, I added the new pair of geospatial properties.
It works fine on my side with your endpoint. Please double-check.

I also added sdo: (the https one) and schema: (the http one) as a default prefixes for more conventional SPARQL queries (visible in the YASGUI view).

Important note: if properties schema:position and/or schema:logo properties were used to control the display of suggestions, they need to be replaced by the sdo: versions.

**Comment by wouterbeek** [comment]
@sebferre Thanks for looking into this!

I do not see the map functionality yet.  This is how it looks on my side:
![Screenshot from 2021-05-27 07-09-42](https://user-images.githubusercontent.com/1685012/119769367-a23c7e00-beba-11eb-81b6-9f281b55031d.png)

^ I'm expecting the "Map" tab to become active.

(This is with the online version that is tagged "Last modified May 26th, 2021" at the bottom of the web page.)

**Comment by sebferre** [comment]
Here is the [query](https://rebrand.ly/f5rhp1a) that shows a map.
To get the map, the special suggestion 'that has a geolocation' must be selected rather than individual properties for latitude and longitude. Benefits: a single selection, a trigger for the map, latitude and longitude columns are not shown in the table of results.

**Comment by kad-beekw** [comment]
Thanks @sebferre !  The "has a geolocation" option works well.  Closing...
